#!/usr/bin/python3

import socket

import dnslib

def main():
  s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
  s.bind(('224.0.0.251', 5353))
  q = dnslib.DNSRecord.question('_adb-tls-connect._tcp.local', 'PTR')
  s.sendto(q.pack(), ('224.0.0.251', 5353))
  while True:
    res, peer = s.recvfrom(4096)
    a = dnslib.DNSRecord.parse(res)
    if not a.rr: # our request
      continue
    # print port from last SRV records
    # because it takes time for old port to disappear
    # hopefully we've taken the right one
    for r in reversed(a.ar):
      if r.rtype == dnslib.QTYPE.SRV:
        port = r.rdata.port
        print(f'{peer[0]}:{port}')
        return

if __name__ == '__main__':
  main()
