#!/usr/bin/env python3
# fileencoding=utf-8

'''从列表中读取备份文件（*~）列表，并检测原文件是否存在；若不存在则删之'''

import sys, os
from path import path
import subprocess
import datetime

f = subprocess.getoutput("locate -e -b '*~' 2> /dev/null").split('\n')

log = open('/home/lilydjwg/etc/log/bakdeleter', 'w')

def filter(f):
  if not os.path.isfile(i[:-1]):
    return True
  now = datetime.datetime.today()
  atime = f.atime
  interval = datetime.timedelta(days=30)
  if now - atime > interval:
    return True
  return False

for i in f:
  f = path(i.rstrip())
  if i.endswith('~') and f.parent().access(os.W_OK):
    if filter(f):
      try:
        f.unlink()
        log.write(i+'\n')
        # print(i)
      except:
        log.write(i+': error'+repr(sys.exc_info())+'\n')

log.close()

