#!/usr/bin/env python3
# vim:fileencoding=utf-8

import sys
import argparse
import subprocess

from pygments import highlight
import pygments.util
from pygments.formatters import TerminalFormatter
from pygments.lexers import guess_lexer, guess_lexer_for_filename

def main(fname, lang):
  code = open(fname).read()
  try:
    lexer = guess_lexer_for_filename(fname, code)
  except pygments.util.ClassNotFound:
    lexer = guess_lexer(code)
  if sys.stdout.isatty():
    p = subprocess.Popen(['less', '-RFX'], stdin=subprocess.PIPE,
                        universal_newlines=True)
    output = p.stdin
  else:
    p = None
    output = sys.stdout
  print(highlight(code, lexer, TerminalFormatter()), file=output)
  output.close()
  if p:
    p.wait()

if __name__ == '__main__':
  parser = argparse.ArgumentParser(description='用 less 显示高亮的代码')
  parser.add_argument('files', metavar='FILE', nargs='+',
                     help='要高亮的文件')
  parser.add_argument('-l', '--lang', dest='lang', default=None,
                     help='语法类型')

  args = parser.parse_args()
  for l in args.files:
    main(l, args.lang)
