#!/usr/bin/env python3
# vim:fileencoding=utf-8

'''
防止 CPU 温度过高
'''

import sys, os, time

sys.path.append('/home/lilydjwg/scripts/python/pylib')
from system import getCPUTemp, setMaxCPUFreq

freqs = {
  'high': 2500 * 1000000,
  'low':  1800 * 1000000,
}

temp = {
  'high': 60,
  'low':  45,
}
logfile = open('/home/lilydjwg/etc/log/cputemp.log', 'a', buffering=1)

def log(fmt, *args):
  print(time.ctime(), end='\t', file=logfile)
  print(fmt % args, file=logfile)

def main():
  state = ''
  while True:
    cputemp = getCPUTemp()
    if state != 'high' and cputemp > temp['high']:
      log('CPU Temperature too high (%f), set CPU frequency to %.1fGHz.',
        cputemp, freqs['low'] / 1000000000)
      setMaxCPUFreq(freqs['low'])
      state = 'high'
    elif state != 'low' and cputemp < temp['low']:
      log('CPU Temperature low (%f), set CPU frequency to %.1fGHz.',
        cputemp, freqs['high'] / 1000000000)
      setMaxCPUFreq(freqs['high'])
      state = 'low'
    elif state == 'high' and cputemp > temp['high']:
      log('CPU Temperature still high (%f).', cputemp)
    time.sleep(2)

if __name__ == '__main__':
  if os.geteuid() != 0:
    print('需要以 root 权限运行', file=sys.stderr)
    sys.exit(1)
  main()
