#!/usr/bin/env python3
# vim:fileencoding=utf-8

'''
参见 http://www.dailiav.com/ssh.html

2010年9月18日
'''

import pexpect
import sys

try:
  ssh = pexpect.spawn('ssh -C -N -D 1080 -o StrictHostKeyChecking=no dailisssss@173.212.209.131')
  ssh.logfile_read = sys.stdout.buffer
  ssh.expect('password:')
  ssh.sendline('www.dailiav.com')
  print()
  print('OK.', end='')
  sys.stdout.flush()
  ssh.wait()
except KeyboardInterrupt:
  print('结束')
