#!/usr/bin/env python3
# vim:fileencoding=utf-8

import os
import sys
from myutils import filesize

if len(sys.argv) == 1:
  for l in sys.stdin:
    n = int(l.strip())
    print(filesize(n))
else:
  sys.exit('%s reads integers one per line from stdin, and print in human-' \
           'readable byte size unit' % os.path.split(sys.argv[0])[1])
