#!/usr/bin/env python3
# vim:fileencoding=utf-8

'''
扫描火狐的配置目录以获取扩展列表
'''

import sys
from lilypath import path
from lxml import etree

def getInfo(extdir):
  doc = etree.parse(str(extdir+'install.rdf'))
  try:
    name = doc.xpath('//em:name', namespaces={'em':'http://www.mozilla.org/2004/em-rdf#'})[0].text
  except IndexError:
    name = doc.xpath('//RDF:Description', namespaces={'RDF':'http://www.w3.org/1999/02/22-rdf-syntax-ns#'})[0]
    name = name.get('{http://www.mozilla.org/2004/em-rdf#}name')
  print(extdir.basename, name, sep='\n', end='\n\n')

def getAllInfo(profdir=path('~/.mozilla/firefox/profile').expand()):
  for i in (profdir+'extensions').dirs():
    getInfo(i)

if __name__ == '__main__':
  if len(sys.argv) == 1:
    getAllInfo()
  elif len(sys.argv) == 2:
    getAllInfo(path(sys.argv[1]))
  else:
    print('参数过多。', file=sys.stderr)
