#!/usr/bin/env python3
# vim:fileencoding=utf-8

'''
获取网页标题，url.py 中 getTitle 函数的测试程序

2010年7月2日
'''

import netservice, sys, socket

if __name__ == '__main__':
  try:
    title = netservice.getTitle(sys.argv[1], defaultCharset='gb18030')
  except socket.timeout:
    print('timed out')
  else:
    if isinstance(title, bytes):
      import chardet
      title = title.decode(chardet.detect(title)['encoding'])
    print(title)
