#!/usr/bin/env python3

import sys

from tornado import gen, ioloop

from mytornado.fetchtitle import TitleFetcher

@gen.coroutine
def main():
  url = sys.argv[1]
  ans = yield gen.Task(TitleFetcher, url)
  title = ans.args[0]
  print(title)

if __name__ == '__main__':
  ioloop.IOLoop.current().run_sync(
    main, timeout=10,
  )
