#!/usr/bin/env python3
# vim:fileencoding=utf-8

'''
金山快盘 之 python 版

2010年11月21日
'''

from lilypath import path, sha1path
from my_class import Config
import kuaipan
from time import sleep

# 用户数据
user_config = Config({
    'username': 'lilydjwg@gmail.com',
    'cookieFile': str(path('~/scripts/python/pydata/kuaipan.cookie').expand()),
    'dest': sha1path('~/workspace/jshan/shares').expand(),
  })

def filtered(file):
  '''不要同步的项，file 为快盘文件字典'''
  if file['name'].endswith('~'):
    return True

def syncShare():
  s = kuaipan.KSession(user_config['username'], user_config['cookieFile'])
  shares = s.getsharetome()
  shtrees, ids = kuaipan.getTree(shares)
  rootpath = user_config['dest']
  for d in shtrees:
    root = rootpath + d['name']
    for f, p in kuaipan.traverse(d, root):
      if not p.exists():
        p.mkdir()
      dst = p + f['name']
      if filtered(f):
        print('忽略', str(dst)[len(str(user_config['dest']))+1:])
        continue
      if dst.exists():
        pf = kuaipan.kpath(f, ids)
        if pf == dst:
          print('跳过', str(dst)[len(str(user_config['dest']))+1:])
          continue
      try:
        s.download(f, p)
      except kuaipan.KuaipanException as e:
        if 'timeout' in e.msg:
          sleep(1)
        else:
          raise

if __name__ == '__main__':
  syncShare()

