#!/usr/bin/env python3
# fileencoding=utf-8

'''
列出 C/C++ 源文件的第二行的文字（程序摘要）
如果没有指定文件，使用当前目录下的所有文件

2010年8月11日
'''

import os, sys

if len(sys.argv) > 1:
  files = sys.argv[1:]
else:
  files = os.listdir('.')

for i in files:
  if i.endswith('.c') or i.endswith('.cpp') or i.endswith('.h'):
    try:
      f = open(i, encoding='utf-8')
      f.readline()
      l = f.readline()
    except UnicodeDecodeError:
      f = open(i, encoding='gb18030')
      f.readline()
      l = f.readline()
    l = l.strip('/*\n\r ')
    print(i.ljust(30), l)
    f.close()

