#!/usr/bin/python3

import sys
import json

from myopenai import print_streaming_response, App, set_process_name

DEFAULT_MODEL = {
  'local': 'Hy-MT2-1.8B',
  'gemini': 'gemma-4-26b-a4b-it',
}

def detect_language(app: App, text: str) -> str:
  messages = [{
    'role': 'system',
    'content': '你是语言识别器，你会以JSON格式以中文输出用户给出文本的语言名称。',
  }, {
    'role': 'user',
    'content': text,
  }]
  extra = {
    "response_format": {
      "type": "json_schema",
      "json_schema": {
        "name": "translation result",
        "schema": {
          "type": "object",
          "properties": {
            "language": {
              "type": "string",
              "description": "原文的语言名称"
            },
          },
          "required": ["language"],
        }
      }
    }
  }

  r = app.request(messages, extra=extra)
  r = r.json()['choices'][0]['message']['content']
  r = json.loads(r)
  return r['language']

def main(args) -> None:
  model = args.model or DEFAULT_MODEL[args.api]
  app = App(args.api, model)

  data = sys.stdin.read()
  if args.lang is None:
    prompt = f'将以下文本翻译为简体中文，注意只需要输出翻译后的结果，不要额外解释：\n{data}'
  else:
    prompt = f'Translate the following segment into {args.lang}, without additional explanation.\n{data}'

  if args.orig_lang:
    lang = detect_language(app, data)
    print(lang)

  messages = [{
    'role': 'system',
    'content': '你是忠实的语言翻译器',
  }, {
    'role': 'user',
    'content': prompt,
  }]

  with app.stream(messages) as r:
    print_streaming_response(r)

if __name__ == '__main__':
  set_process_name('llama-trans')

  import argparse
  parser = argparse.ArgumentParser()
  parser.add_argument('--orig-lang', action='store_true',
                      help='detect original language')
  parser.add_argument('lang', nargs='?',
                      help='target language')
  App.add_common_argument(parser, default_api='local')
  args = parser.parse_args()

  try:
    main(args)
  except KeyboardInterrupt:
    print()
    sys.exit(130)
