#!/usr/bin/python3

import sys
import base64

DEFAULT_MODEL = 'gemma-4-26b-a4b-it'

from myopenai import print_streaming_response, App, set_process_name

def main(args) -> None:
  data = sys.stdin.buffer.read()
  data = base64.b64encode(data).decode('ascii')

  content = []
  if args.prompt:
    content.append({
      'type': 'text',
      'text': args.prompt,
    })

  content.append({
    'type': 'image_url',
    'image_url': {
      'url': 'data:image/png;base64,' + data,
    },
  })

  app = App(args.api, args.model or DEFAULT_MODEL)

  messages = [{
    'role': 'user',
    'content': content,
  }]
  with app.stream(messages) as r:
    print_streaming_response(r)

if __name__ == '__main__':
  set_process_name('llama-ocr')

  import argparse

  parser = argparse.ArgumentParser()
  parser.add_argument('prompt', nargs='?',
                      help='optional prompt')
  App.add_common_argument(parser, default_api='local')
  args = parser.parse_args()

  main(args)
