#!/usr/bin/python3

from myopenai import Client, set_process_name

DEFAULT_MODEL = 'gemini-3.1-flash-lite'
# DEFAULT_MODEL = 'gemini-3.5-flash'
# DEFAULT_MODEL = 'gemma-4-26b-a4b-it'

def main(args):
  app = Client(args.api, args.model or DEFAULT_MODEL)
  messages = [{
    'role': 'system',
    'content': '请简洁扼要地回复',
  }]
  app.interact(messages)

if __name__ == '__main__':
  set_process_name('llama-talk')

  import argparse

  parser = argparse.ArgumentParser()
  Client.add_common_argument(parser, default_api='gemini')
  args = parser.parse_args()

  main(args)
