#!/usr/bin/env python3
# vim:fileencoding=utf-8

'''
将文件加入 nginx 的下载目录以便下载

2010年9月24日
'''

import sys, os
import subprocess
from urllib.parse import quote as URIescape

destDir = os.path.expanduser('~/.nginx/www/dl')
# myip = subprocess.getoutput('myip')

def lnn(f):
  path = os.path.realpath(os.path.abspath(f))
  name = os.path.split(f)[1]
  os.symlink(path, os.path.join(destDir, name))
  showurl(name)

def showurl(name):
  url = 'http://www.lilydjwg.cjb.net:4321/dl/%s' % \
      URIescape(name)
  print(url)
  print(url.replace('cjb', 'c不要j屏蔽b'), '(去掉中文)')

if __name__ == '__main__':
  if len(sys.argv) > 1:
    for f in sys.argv[1:]:
      try:
        lnn(f)
      except OSError as e:
        if e.errno == 17:
          showurl(os.path.split(f)[1])
        else:
          print('Error %d: %s' % (e.errno, e.strerror), file=sys.stderr)
  else:
    print('Usage: lnn FILE ...')

