#!/usr/bin/env python3
# vim:fileencoding=utf-8

'''
wait some time before actually sending the mail so that one can kill it if
something was wrong
'''

WAIT_TIME = 5

import os
import sys
import time

#TODO better way to set program name?

def set_proc_name(newname):
    from ctypes import cdll, byref, create_string_buffer
    libc = cdll.LoadLibrary('libc.so.6')
    buff = create_string_buffer(len(newname)+1)
    buff.value = newname.encode()
    libc.prctl(15, byref(buff), 0, 0, 0)

def get_proc_name():
    from ctypes import cdll, byref, create_string_buffer
    libc = cdll.LoadLibrary('libc.so.6')
    buff = create_string_buffer(128)
    # 16 == PR_GET_NAME from <linux/prctl.h>
    libc.prctl(16, byref(buff), 0, 0, 0)
    return buff.value

if __name__ == '__main__':
  set_proc_name('msmtp')
  time.sleep(WAIT_TIME)
  os.execlp('msmtp', 'msmtp', *sys.argv[1:])
