#!/usr/bin/env python3
# vim:fileencoding=utf-8

'''
wait some time before actually sending the mail so that one can kill it if
something was wrong
'''

WAIT_TIME = 5

import os
import sys
import time

import setproctitle

if __name__ == '__main__':
  setproctitle.setproctitle('msmtp')
  time.sleep(WAIT_TIME)
  os.execlp('msmtp', 'msmtp', *sys.argv[1:])
