#!/usr/bin/env python3
# vim:fileencoding=utf-8

import os
from bottle import route, run, request, redirect

'''
通过浏览器向 privoxy 的 action 文件中添加项目

2010年12月8日
'''

actionfile = '~/.privoxy/mine.action'

@route('/privoxy/add', method='POST')
def privoxy_add():
  form_data = request.POST
  url = form_data['url']
  proxy = form_data['proxy']
  dest = form_data['dest']
  cmd = '''sed -i -e '/^{%s}$/a\\\n%s' ''' % (proxy, url.replace('\\', r'\\'))
  cmd += actionfile
  st = os.system(cmd)
  if st == 0:
    redirect(dest)
  else:
    return 'Err: %d' % st

run(port='1231') # This starts the HTTP server

