#!/usr/bin/env python3
# fileencoding=utf-8

'''
寻找并删掉独立的 pyc 文件

2010年6月11日
'''

import sys, os
import subprocess

def filefilter(f):
  if i.endswith('ubuntu2.pyc'):
    return False
  return True

f = subprocess.getoutput("find /home/lilydjwg/scripts/py* -name '*.pyc' 2> /dev/null").split('\n')

for i in f:
  i = i.rstrip()
  if i.endswith('.pyc'):
    if filefilter(i) and not os.path.isfile(i[:-1]):
      try:
        if input('删除 %s 吗？' % i) in ('y', 'Y'):
          os.remove(i)
          print(i, '已删除。')
      except:
        print(i+': error'+repr(sys.exc_info()), file=sys.stderr)

