#!/usr/bin/env python3
# vim:fileencoding=utf-8

import os
from rcfile import rcfile

def main():
  rc = rcfile(os.path.expanduser('~/scripts/python/pydata/rcfile.yaml'))
  rc.update()

if __name__ == '__main__':
  main()
