#!/usr/bin/env python3
# vim:fileencoding=utf-8

'''
当 Emapthy 在消息提示时，利用 xmacroplay 打开它

2010年7月24日
'''

import os, pty, time

def terminal_exec(cmd):
  pid, fd = pty.fork()
  if pid == 0: # 子进程
    os.execlp(cmd[0], *cmd)
  else:
    return fd

def main():
  cmd = ['xmacroplay', os.environ['DISPLAY']]
  fd = terminal_exec(cmd)
  time.sleep(0.5)
  os.write(fd, b'KeyStrPress Super_L\n')
  os.write(fd, b'KeyStr m\n')
  os.write(fd, b'KeyStrRelease Super_L\n')
  os.read(fd, 1024)
  os.write(fd, b'KeyStr Up\n')
  os.write(fd, b'KeyStr Return\n')
  os.read(fd, 1024)
  time.sleep(0.1)
  os.close(fd)

if __name__ == '__main__':
  main()
