#!/usr/bin/env python3
# vim:fileencoding=utf-8

'''
显示 pickled 文件的内容

2010年10月31日
'''

import sys
import pickle

def show(file):
  print(repr(pickle.loads(open(file, 'rb').read(), encoding='utf-8')))

if __name__ == '__main__':
  if len(sys.argv) == 1:
    print('请给出要显示的 pickled 文件')
  for l in sys.argv[1:]:
    show(l)

