#!/usr/bin/env python3
# vim:fileencoding=utf-8

from todo import *
import sys
import os

file = os.path.expanduser('~/scripts/python/pydata/todo')

def main():
  T = TODO(file)
  try:
    T(sys.argv[1:])
  except (NoSuchCommand, CommandError) as e:
    print(e)

if __name__ == '__main__':
  main()

