#!/usr/bin/env python3
# fileencoding=utf-8

'''
为 zsh 的 kill 补全所写，去除 argv[0] 中的路径

  zstyle ':completion:*:processes' command 'ps -afu$USER|trimdir'

2010年6月17日
'''

import sys, os, re

argv0 = re.compile(r'(?<=\d{2}:\d{2} )\S+')

def trimdir(match):
  return os.path.basename(match.group(0))

def trim():
  l = sys.stdin.readline()
  while l:
    print(argv0.sub(trimdir, l))
    l = sys.stdin.readline()

if __name__ == '__main__':
  trim()


