#!/usr/bin/env python3

'''strace wrapper'''

import os
import sys
import subprocess

import expect

def main():
  tracer = sys.argv[1]
  if tracer not in ('strace', 'ltrace'):
    sys.exit('%s not supported.' % tracer)

  vimp = expect.Expect()
  r, w = os.pipe()
  os.set_inheritable(r, True)
  vimp.spawn(["vim", "-R", "/proc/self/fd/%d" % r], preexec_fn = os.setpgrp)
  os.close(r)
  tracerp = subprocess.Popen(
    [tracer] + sys.argv[2:],
    stderr = w,
  )
  try:
    tracerp.wait()
  except KeyboardInterrupt:
    pass
  finally:
    os.close(w)
  vimp.send(b':setf strace\r')
  vimp.interact()

if __name__ == '__main__':
  try:
    import setproctitle
    setproctitle.setproctitle('vimtrace')
  except ImportError:
    pass

  main()
