#!/usr/bin/python3

import sys
import subprocess
import tempfile
from pathlib import Path
import shlex

import httpx

from myopenai import print_streaming_response, App, set_process_name

DEFAULT_MODEL = 'gemini-3.1-flash-lite'
# DEFAULT_MODEL = 'gemini-3.5-flash'
# DEFAULT_MODEL = 'gemma-4-26b-a4b-it'
PROMPT = '根据以下字幕文本总结视频内容。总结结果中请不要包含任何赞助商推广信息。'

def main(args) -> None:
  if args.ytdlp_arg:
    extra_args = shlex.split(args.ytdlp_arg)
  else:
    extra_args = []

  app = App(args.api, args.model or DEFAULT_MODEL)

  with tempfile.TemporaryDirectory() as d:
    subprocess.run([
      'yt-dlp', '--sub-langs', args.lang, '--write-subs', '--write-auto-subs', '--skip-download',
      *extra_args,
      args.url,
    ],
      cwd=d,
      check=True,
    )

    p = Path(d)
    try:
      file = tuple(p.iterdir())[0]
    except IndexError:
      sys.exit('No subtitles.')

    for _ in range(2):
      try:
        do_request(app, file)
        break
      except httpx.ReadError as e:
        print(e, file=sys.stderr)

def do_request(app, filepath: Path) -> None:
  filename = filepath.name
  with filepath.open() as f:
    subtitles = f.read()

  parts = [{
    'role': 'user',
    'content': PROMPT,
  }, {
    'role': 'user',
    'content': f'文件名：{filename}\n文件内容：\n{subtitles}',
  }]

  with app.stream(parts) as r:
    res = print_streaming_response(r)

  parts.append({
    'role': 'assistant',
    'content': ''.join(res),
  })
  app.interact(parts)

if __name__ == '__main__':
  set_process_name('yt-summarize')

  import argparse

  parser = argparse.ArgumentParser()
  parser.add_argument('url',
                      help='YouTube URL')
  parser.add_argument('--lang', default='en',
                      help='choose subtitles language')
  parser.add_argument('--ytdlp-arg',
                      help='extra args to pass to yt-dlp')
  App.add_common_argument(parser, default_api='gemini')
  args = parser.parse_args()

  main(args)
