#!/usr/bin/python3

import sys
import subprocess
import tempfile
from pathlib import Path
import shlex
import os

import httpx

from myopenai import print_streaming_response, interact

URL = 'https://generativelanguage.googleapis.com/v1beta/openai/chat/completions'
DEFAULT_MODEL = 'gemini-3.1-flash-lite'
# DEFAULT_MODEL = 'gemini-3.5-flash'
# DEFAULT_MODEL = 'gemma-4-26b-a4b-it'
PROMPT = '根据以下字幕文本总结视频内容。总结结果中请不要包含任何赞助商推广信息。'

def main(url, model, sublang, ytdlp_arg):
  if ytdlp_arg:
    extra_args = shlex.split(ytdlp_arg)
  else:
    extra_args = []

  with tempfile.TemporaryDirectory() as d:
    subprocess.run([
      'yt-dlp', '--sub-langs', sublang, '--write-subs', '--write-auto-subs', '--skip-download',
      *extra_args,
      url,
    ],
      cwd=d,
      check=True,
    )

    p = Path(d)
    try:
      file = tuple(p.iterdir())[0]
    except IndexError:
      sys.exit('No subtitles.')

    for _ in range(2):
      try:
        do_request(model, file)
        break
      except httpx.ReadError as e:
        print(e, file=sys.stderr)

def do_request(model, filepath):
  client = httpx.Client(
    http2=True,
    headers={
      'Authorization': f'Bearer {os.environ['GEMINI_API_KEY']}',
    }
  )
  filename = filepath.name
  with filepath.open() as f:
    subtitles = f.read()

  parts = [{
    'role': 'user',
    'content': PROMPT,
  }, {
    'role': 'user',
    'content': f'文件名：{filename}\n文件内容：\n{subtitles}',
  }]

  j = {
    'model': model,
    'messages': parts,
    'stream': True,
  }
  with client.stream('POST', URL, json=j, timeout=120) as r:
    res = print_streaming_response(r)

  parts.append({
    'role': 'assistant',
    'content': ''.join(res),
  })
  interact(client, URL, model, parts)

if __name__ == '__main__':
  import argparse

  parser = argparse.ArgumentParser()
  parser.add_argument('URL',
                      help='YouTube URL')
  parser.add_argument('--lang', default='en',
                      help='choose subtitles language')
  parser.add_argument('-m', '--model', default=DEFAULT_MODEL,
                      help='model name to use')
  parser.add_argument('--ytdlp-arg',
                      help='extra args to pass to yt-dlp')
  args = parser.parse_args()

  main(args.URL, args.model, args.lang, args.ytdlp_arg)
