#!/usr/bin/env python3
# vim:fileencoding=utf-8

'''
比较两个词频记录文件

2010年11月21日
'''

import os
from sys import argv, stderr
from re import split
import datetime

same = {}
diff = {}
added = {}
delete = {}

def compare(file1, file2):
  '''file1: 原文件; file2: 新文件.'''

  f1 = open(file1, encoding='gb18030')
  cp1 = {}
  l = f1.readline().strip()
  while l:
    if l.find('#') == 0:
      time1 = datetime.datetime.strptime(l[l.find('：')+1:], '%Y-%m-%d %H:%M')
      l = f1.readline().strip()
      continue
    i = split(' +(?=\d)', l)
    cp1[i[0]] = i[1:]
    l = f1.readline().strip()
  f1.close()

  f2 = open(file2, encoding='gb18030')
  cp2 = {}
  l = f2.readline().strip()
  while l:
    if l.find('#') == 0:
      time2 = datetime.datetime.strptime(l[l.find('：')+1:], '%Y-%m-%d %H:%M')
      l = f2.readline().strip()
      continue
    i = split(' +(?=\d)', l)
    cp2[i[0]] = i[1:]
    l = f2.readline().strip()
  f2.close()

  for i in cp2:
    if i in cp1:
      if cp1[i] == cp2[i]:
        same[i] = cp2[i]
      else:
        diff[i] = cp1[i] + cp2[i]
    else:
      added[i] = cp2[i]

  for i in cp1:
    if i not in cp2:
      delete[i] = cp1[i]

  print('[新增]')
  for i in added:
    print(i[:i.find(' ')].ljust(5), i[i.find(' ')+1:].ljust(10, '　').replace('　', '  '), added[i][0].rjust(5), added[i][1].rjust(5))
  print('\n[修改]')
  for i in diff:
    print(i[:i.find(' ')].ljust(5), i[i.find(' ')+1:].ljust(10, '　').replace('　', '  '), diff[i][0].rjust(5), diff[i][1].rjust(7), diff[i][2].rjust(5), diff[i][3].rjust(7))
  print('\n[删除]')
  for i in delete:
    print(i[:i.find(' ')].ljust(5), i[i.find(' ')+1:].ljust(10, '　').replace('　', '  '), delete[i][0].rjust(5), delete[i][1].rjust(5))
  print('\n[相同]')
  for i in same:
    print(i[:i.find(' ')].ljust(5), i[i.find(' ')+1:].ljust(10, '　').replace('　', '  '), same[i][0].rjust(5), same[i][1].rjust(6))

  print()
  print(time2 - time1)
  print('新增', str(len(added)).rjust(4), '项；')
  print('修改', str(len(diff)).rjust(4), '项；')
  print('删除', str(len(delete)).rjust(4), '项；')
  print('相同', str(len(same)).rjust(4), '项。')

if __name__ == '__main__':
  if os.path.isfile(argv[1]) and os.path.isfile(argv[2]):
    compare(argv[1], argv[2])
  else:
    stderr.write('文件不存在！')
