#!/bin/zsh

emulate -L zsh
cd $(dirname $0)
PS4=
: ${CC:=gcc}

makeaso () {
  infile=$1
  outfile=../pylib/_${infile%.*}.so
  if [[ $outfile -nt $infile ]]; then
    return
  fi
  shift
  setopt -x
  $CC $@ -O2 -shared -fPIC $infile -o $outfile
}

makeaso ard.c
makeaso wchar.c
